### ISSUE TITLE
How to override overflow-x style of the main Highlight div 

### ISSUE THREAD

**Issue by isaacwein** [metonym/svelte-highlight#280]
already talked about this in issue #274 

I can't make it work even if I define a global class because the overflow-x is on the div itself, why make it so hard?
```html
<div class="line-numbers svelte-1vh31p0" style="overflow-x: auto;"> 
    <table class="svelte-1vh31p0">
          ....
    </table>
</div>
```

the only way i was able to overwrite it was with a `!important` like this
```css
.line-numbers {
  overflow-x: unset !important;
  overflow-y: unset !important;
}
```
i don't think it is the right way
the whole think that i need to define it as a global class is wrong to begin with
