### ISSUE TITLE
[Feature Request] Add ability to change padding on langtag

### ISSUE THREAD

**Issue by samhsabin** [metonym/svelte-highlight#324]
Right now the default padding for langtag is massive, making it more of a full corner div than a "tag". Would be nice if we could adjust the padding and distance from the top right so we could make it appear like a tag.

**Comment by metonym** [comment]
What is your current workaround?

**Comment by samhsabin** [comment]
I just to not style it at all because I couldn't create something I was happy with

**Comment by metonym** [comment]
A workaround is to use global CSS to override the style. I'll look into adding a style prop to make this customization easier.

```css
<style>
  :global([data-language="css"]:after) {
    padding: 0.5rem !important;
  }
</style>
```
