### ISSUE TITLE
Optimize CSS styles

### ISSUE THREAD

**Issue by metonym** [metonym/svelte-highlight#356]
Some CSS styles contain duplicate rules, e.g., `3024.css`

```css
pre code.hljs {
  display: block;
  overflow-x: auto;
  padding: 1em;
}
code.hljs {
  padding: 3px 5px;
}

pre code.hljs {
  display: block;
  overflow-x: auto;
  padding: 1em;
}
code.hljs {
  padding: 3px 5px;
}
```
